#!/usr/bin/env python3
import json
import os
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SPEC = ROOT.parent / "webscraping-api" / "dist" / "openapi.public.json"
SPEC_PATH = Path(os.environ.get("CRAWLORA_OPENAPI_SPEC", DEFAULT_SPEC))
TAG_GROUP_OVERRIDES = {
    "AppStore": "AppStore",
    "CoinGecko": "CoinGecko",
    "GooglePlay": "GooglePlay",
    "ProductHunt": "ProductHunt",
    "SimilarWeb": "SimilarWeb",
    "SpotifyPodcasts": "SpotifyPodcasts",
    "TikTok": "TikTok",
    "YouTube": "YouTube",
}
TAG_PREFIX_OVERRIDES = {
    "AppStore": "appstore",
    "CoinGecko": "coingecko",
    "GooglePlay": "googleplay",
    "ProductHunt": "producthunt",
    "SimilarWeb": "similarweb",
    "SpotifyPodcasts": "spotify-podcasts",
    "TikTok": "tiktok",
    "YouTube": "youtube",
}


def words(value):
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", value)
    return [part for part in re.split(r"[^A-Za-z0-9]+", value.lower()) if part]


def pascal(parts):
    return "".join(part[:1].upper() + part[1:] for part in parts) or "Call"


def alias(operation_id, tag, used):
    op_words = words(operation_id)
    tag_words = words(TAG_PREFIX_OVERRIDES.get(tag, tag))
    if op_words[: len(tag_words)] == tag_words:
        op_words = op_words[len(tag_words) :]
    name = pascal(op_words)
    if not name or name in used:
        name = pascal(words(operation_id))
    base = name
    i = 2
    while name in used:
        name = f"{base}{i}"
        i += 1
    used.add(name)
    return name


def go_string(value):
    return json.dumps(value)


def go_string_slice(values):
    return "[]string{" + ", ".join(go_string(v) for v in values) + "}"


def param_slice(params):
    if not params:
        return "nil"
    items = []
    for param in params:
        collection = param.get("collectionFormat", "")
        typ = param.get("type", "")
        items.append(
            "parameterDefinition{Name: "
            + go_string(param["name"])
            + ", CollectionFormat: "
            + go_string(collection)
            + ", Type: "
            + go_string(typ)
            + "}"
        )
    return "[]parameterDefinition{" + ", ".join(items) + "}"


def definition(method, path, operation):
    params = operation.get("parameters", [])
    security = []
    for requirement in operation.get("security", []):
        security.extend(requirement.keys())
    path_params = [p["name"] for p in params if p.get("in") == "path"]
    query_params = [p for p in params if p.get("in") == "query"]
    form_params = [p for p in params if p.get("in") == "formData"]
    body_param = next((p["name"] for p in params if p.get("in") == "body"), "")
    return (
        "operationDefinition{"
        f"Method: {go_string(method.upper())}, "
        f"Path: {go_string(path)}, "
        f"PathParams: {go_string_slice(path_params)}, "
        f"QueryParams: {param_slice(query_params)}, "
        f"FormParams: {param_slice(form_params)}, "
        f"BodyParam: {go_string(body_param)}, "
        f"Security: {go_string_slice(security)}, "
        "}"
    )


def main():
    if not SPEC_PATH.exists():
        raise SystemExit(f"public OpenAPI spec not found: {SPEC_PATH}")
    spec = json.loads(SPEC_PATH.read_text())
    (ROOT / "openapi").mkdir(exist_ok=True)
    shutil.copyfile(SPEC_PATH, ROOT / "openapi" / "public.json")

    operations = {}
    groups = {}
    used_by_group = {}
    for path, methods in sorted(spec["paths"].items()):
        for method, operation in sorted(methods.items()):
            operation_id = operation["operationId"]
            tag = (operation.get("tags") or ["Default"])[0]
            group_name = TAG_GROUP_OVERRIDES.get(tag, pascal(words(tag)))
            groups.setdefault(group_name, {})
            used_by_group.setdefault(group_name, set())
            method_name = alias(operation_id, tag, used_by_group[group_name])
            groups[group_name][method_name] = operation_id
            operations[operation_id] = definition(method, path, operation)

    lines = [
        "package crawlora",
        "",
        'import "context"',
        "",
        "// Generated by scripts/generate.py. Do not edit manually.",
        "",
        "type parameterDefinition struct {",
        "\tName string",
        "\tCollectionFormat string",
        "\tType string",
        "}",
        "",
        "type operationDefinition struct {",
        "\tMethod string",
        "\tPath string",
        "\tPathParams []string",
        "\tQueryParams []parameterDefinition",
        "\tFormParams []parameterDefinition",
        "\tBodyParam string",
        "\tSecurity []string",
        "}",
        "",
        "var operations = map[string]operationDefinition{",
    ]
    for operation_id, body in operations.items():
        lines.append(f"\t{go_string(operation_id)}: {body},")
    lines.extend(["}", "", "type Services struct {"])
    for group_name in groups:
        lines.append(f"\t{group_name} *{group_name}Service")
    lines.extend(["}", "", "func initServices(c *Client) Services {", "\treturn Services{"])
    for group_name in groups:
        lines.append(f"\t\t{group_name}: &{group_name}Service{{client: c}},")
    lines.extend(["\t}", "}", ""])
    for group_name, methods in groups.items():
        lines.append(f"type {group_name}Service struct {{ client *Client }}")
        lines.append("")
        for method_name, operation_id in methods.items():
            lines.append(f"func (s *{group_name}Service) {method_name}(ctx context.Context, params Params) (any, error) {{")
            lines.append(f"\treturn s.client.Request(ctx, {go_string(operation_id)}, params)")
            lines.append("}")
            lines.append("")
    (ROOT / "operations_generated.go").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
